### ISSUE TITLE
the demo in the project seems to be inaccessible

### ISSUE THREAD

**Issue by studentyyh** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#115]
Hello, the demo in the project seems to be inaccessible, is there something wrong?

**Comment by becauseofAI** [comment]
Why is this website of ```http://semantic-sam.xyzou.net:6090/``` inaccessible?

**Comment by MaureenZOU** [comment]
fixed : )

**Comment by becauseofAI** [comment]
> fixed : )

Thx!
Can you fix the Semantic-SAM demo again?
The demo website are ```http://semantic-sam.xyzou.net:6098/``` and ```http://semantic-sam.xyzou.net:6080/```.
Thx again. @MaureenZOU

**Comment by tjucwb** [comment]
> @MaureenZOU

sorry to interrupt, i still have problem  opening it, is it accessible now?

**Comment by huzongxiang** [comment]
very bad project
